# Generated by Django 3.1.14 on 2025-02-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customer_id_alter_user_id'),
        ('users', '0019_auto_20250219_0715'),
    ]

    operations = [
    ]
