# Generated by Django 3.1.14 on 2025-02-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20250226_0958'),
        ('users', '0023_auto_20250227_0952'),
    ]

    operations = [
    ]
