# Generated by Django 3.1.14 on 2025-02-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20250213_1919'),
        ('services', '0012_auto_20250213_1123'),
    ]

    operations = [
    ]
