# Generated by Django 3.1.14 on 2025-02-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_service_id_alter_servicerequest_id'),
        ('services', '0018_auto_20250219_0715'),
    ]

    operations = [
    ]
