# Generated by Django 3.2.20 on 2025-02-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250217_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
