# Generated by Django 3.1.14 on 2025-02-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20250227_0952'),
        ('company', '0014_auto_20250226_0958'),
    ]

    operations = [
    ]
